src/opl/generator.cpp

fixed out of bounds access in the channel array

---

CMakeLists.txt

add cmake project file

---

src/opl/generator.cpp

load null instrument in generator to prevent crash

---

src/audio.cpp
src/bank_editor.cpp
src/bank_editor.h
src/bank_editor.ui

Enables instrument navigation and piano play on the keyboard at the same time

focus restored on intruments with key event filter

---

src/opl/generator.cpp

#49 
I think this is the correct fix.

fix a crash on noteoff

---

CMakeLists.txt
FMBankEdit.pro
src/audio.cpp
src/audio/ao_rtaudio.cpp
src/bank_editor.cpp
src/bank_editor.h
src/bank_editor.ui
src/latency.cpp
src/latency.h

This patch allows to define the latency in GUI and save it in settings.
It seems I have been in file conflicts because we have edited the same menus!
I see you have been busy on Win9x work!

Very low latency part 1/2

---

src/audio/ao_rtaudio.cpp
src/audio/ao_rtaudio.h

#51 
I give you the audio error callback with stderr message printing

enable audio error callback with printing

---

src/opl/generator_realtime.h

for Qt4, make changeNote() a slot and adapt the signature

---

src/opl/generator_realtime.cpp

It's another stupid thing for which you're going to scold me :grin: 
Caught a mistake which would corrupt FIFO when both ctl and midi would play.
By the way, I have tested ASIO on non-virtualized Windows. It's perfect.

fix a mistake of FIFO usage

---

src/opl/generator_realtime.cpp

I've been testing generator and note manager by sending MIDI files into it. Good so far.
I just add some trivial midi messages support.

support MIDI message: all sound off, all notes off

---

src/ins_names.cpp

This mistake is in all the projects, and genadldata, so I have to also fix it in all others..

fix a misspelling of instrument: distortion guitar

---

src/resources/opl3_bank_editor.desktop

It should be even greater if it could be installed by the cmake/qmake system then even someone compiling the program would get a menu item.
Unfortunately, I don't know how to do so so I'm leaving that to you the coding people!

Add a desktop file for packagers

---

CMakeLists.txt
src/resources/mime/opl3-opli.xml
src/resources/mime/opl3-wopl.xml
src/resources/opl3_bank_editor.desktop

#77 
It's very basic. No detection by magic, no icon, only WOPL and WOPI.
Linux/BSD

add basic file associations for freedesktop (WOPL/WOPI)

---

CMakeLists.txt
FMBankEdit.pro
_Misc/qt-4-4-3-build/Readme.txt
cmake/FindQwt.cmake
src/bank_editor.cpp
src/bank_editor.h
src/bank_editor.ui
src/delay_analysis.cpp
src/delay_analysis.h
src/delay_analysis.ui
src/opl/measurer.cpp
src/opl/measurer.h
src/translations/opl3bankeditor_fr_FR.ts

Added a simple dialog to visualize the sound delays with plots.
It has the option to be compiled or not. Library used was Qwt which must be Qt 4 compatible.
Color scheme is not great, it would be better if changed later.

Analyze delays2

---

CMakeLists.txt

This removal got mixed by me in the last merge by a mistake.

add a cmake installation part removed by mistake

---

src/bank_editor.ui
src/translations/opl3bankeditor_fr_FR.ts
src/translations/opl3bankeditor_ru_RU.ts

Just change a tooltip text.
I will make all identical strings matching with the OPN editor. Fixing some of the mistakes on the way.

fix an english error and update translations accordingly

---

README.md

Update README.md re: compilation

---

README.md
src/FileFormats/format_ail2_gtl.cpp

Correct a few errors in text.
- concatenated #102 
- miswritten "AdLib Timbre"

fix various errors in text

---

src/audio.cpp
src/piano.cpp
src/piano.h

highlight piano keys pressed by keyboard

---

src/bank_editor.cpp
src/bank_editor.h

instrument copy in the global clipboard

---

src/FileFormats/format_sb_ibk.cpp

#107 
This is the code by which I attempted to pass JuceOPLVSTi SBI as normal SBI.
By this process the instruments seemed to sound fine.
I don't have the full certainty that I picked the right kind of SBI as I did this, I just picked what I considered as the nearest thing.
related: https://github.com/bsutherland/JuceOPLVSTi/issues/74

support SBI from JuceOPLVSTi

---

src/FileFormats/wopl/wopl_file.c

This will create at least 1 bank and load it with an empty instrument set.

allow to load a WOPL which has no melodics or no drums

---

src/bank.cpp
src/bank.h
src/importer.cpp
src/importer.ui
src/translations/opl3bankeditor_fr_FR.ts

The same importer work for OPL3 as made on OPN2-BE.

Importer work

---

README.md
changelog.txt

See https://github.com/Wohlstand/OPL3BankEditor/commit/14b47a21d63c45c3c29e7f67dfbb6e779cba7d63
Hope that helps

Mention to newly added Adlib Gold BNK file format

---

src/FileFormats/ymf262_to_wopi.cpp

Fix a case of badly checked 4op register.

dro: fix the 4op detection

---

src/FileFormats/ymf262_to_wopi.cpp

- fixes an issue when certain channel's registers will be unrecognized
- increases carrier volume

Dro importer fix

---

src/ins_names.h

Same resolution of instrument lookup trouble on Windows

compatible bit-packing under Windows

---

src/FileFormats/format_vgm_import.cpp

OPL3 high register needs one more bit..

vgm: fix a truncation of OPL register value

---

src/FileFormats/ymf262_to_wopi.cpp
src/FileFormats/ymf262_to_wopi.h

#126
Added rhythm-mode instrument importer

raw importer for rhythm-mode instruments

---

CMakeLists.txt
FMBankEdit.pro
src/bank_comparison.cpp
src/bank_comparison.h
src/bank_comparison.ui
src/bank_editor.cpp
src/bank_editor.h
src/bank_editor.ui
src/metaparameter.h
src/translations/opl3bankeditor_fr_FR.ts

#141
Made experimental bank difference tool.
"Edit" menu > "Compare with other bank"

bank diff tool

---

CMakeLists.txt
FMBankEdit.pro
src/FileFormats/format_vgm_import.cpp
src/FileFormats/format_vgm_import.h

- skip the proper number of bytes on opcode unknown
- correct positioning of data beginning, according to file version and field value
EDIT update just for the code style, sorry to annoy

vgm reader fixes

---

src/opl/chips/opl_serial_port.cpp
src/opl/chips/opl_serial_port.h

Continuing the serial port work here.
Building a Windows version that can help the debugging.
It can be a threading issue which is the origin of QSerialPort trouble, I'm going to check it..

Serial port

---

src/translations/opl3bankeditor_pl_PL.ts

Improved wording, syntax, grammar, corrected translation of some items.
Poprawiono dobór słów, składnię, gramatykę i przekład niektórych pozycji.

Improve Polish translation

---

src/translations/opl3bankeditor_pl_PL.ts

- Translated description of volume models
- Fixed a stupid typo in waveform selector
- Improved wording a bit in a few spots

update polish translation

---

src/audio.cpp
src/audio/ao_rtaudio.cpp
src/audio/ao_rtaudio.h
src/audio_config.cpp
src/audio_config.h
src/audio_config.ui
src/bank_editor.cpp
src/bank_editor.h

Adds a setting to choose the driver for rtaudio.
Like the device, this becomes effective on next start.

Choice of audio driver
