src/audio/ao_alsa.cpp, src/audio/ao_alsa.h
Use the RAII to make sure to memory blocks are freed in ALSA output.
Not a very important issue, but it's next episode in the AddressSanitizer adventure.
There is some more which pollutes my log, but they may be internal to Qt so it's not sure if I can do anything about it.
=> alsa: make sure to free pcm params in destructor

src/bank_editor.ui, src/main.cpp
I spent some time to reorganize UI layout to fix #26 
This is an attempt.
I have put the hierarchy in layouts which will stretch when the window is resized.
But the window is kept fixed, instead just a single `adjustSize()` is done to let it adjust itself according to the appearance settings and the fonts.
It will be able to work in a range of font sizes.
To keep all things compact like they were, I have fixed maximum sizes for a few elements. This will mean that big font sizes are still going make the text overflow (but seems good up to 14). If this must be fixed, I think the best way is to enforce a font size limit in the source code.
=> flexible ui layout for bank editor

src/bank_editor.cpp, src/bank_editor.h, src/bank_editor.ui, src/main.cpp
Based on @papiezak's feedback on Windows UI, I add a fix and some changes.
I remove a `setFixedSize` call in the main window. It would potentially supersede the automatic adjument of size I have attempted to make, and window would stay in the size defined in the designer file.
(please note now, the window has become resizable by size grip)
Second, I am postponing the adjustment of size at the latest time after the window is shown. It is the best way to ensure everything is set up and well before setting the final size.
Based on the screencap of the Windows version, I have added some margins where I found them appropriate. This time signals-slots are still present and not deleted for whatever reason.
I tried this under Wine. (since this OS has the smallest gui elements, it may have …
=> bank editor: lazy adjustment of size and layout update

src/bank_editor.ui
This is next iteration of the main page UI. What's new in this one:
- correctly resize some of the Decay/Release boxes
- repack some horizontal elements to be smaller in size and reduce overall width (most importantly, Waveform Select)
- make AM/FM centered in their box and with smaller space in between (@papiezak's suggestion)
- make Feedback and Synthesis Type boxes vertically aligned with each other
(the designer software this time has again tried to remove signals behind my back :confused: I was vigilant. I would be happy to move those in source code at some point in time)
=> arrange for compactness and alignment

src/bank_editor.ui
It allows to navigate the instrument list with the keyboard only.
I couldn't think of reasons why this widget was excluded from keyboard focus, when all the other edit widgets were permitted to have it.
=> allow the instrument list to take keyboard focus

src/bank_editor.cpp, src/bank_editor.h, src/bank_editor.ui
The bank editor will keep track of the path name which is displayed in the title label.
Ctrl+S is reassigned to "Save" instead of "Save As".
Depending on action, the new `saveFileAs` function signature is invoked with either file path, or empty string. In the former case, and when a file is current in the editor, the dialog box selection is skipped and the current file name is used.
=> Ctrl-S quick save

src/audio/ao_rtaudio.cpp
Forgot to change client name after copying code out of ADLrt.
Better now:
=> give the audio client the appropriate name

src/midi/midi_rtmidi.cpp
It's a small thing I caught when making the diff with OPN2 sources.
=> undo a std::string copy where not needed

src/bank_editor.cpp
Make "American English" just be "English", to match the UK flag icon en.png
And put a capital letter on the language name.
=> display en_US as generic English, capitalize language name

src/bank_editor.cpp, src/bank_editor.h, src/bank_editor.ui, src/controlls.cpp, src/opl/generator.cpp, src/opl/generator.h, src/opl/generator_realtime.cpp, src/opl/generator_realtime.h
#19 
I implement pitch bend functionality.
On a bend event, I update the bend value, go over the active channels and I invoke the same code as `PlayNoteF` as previously to update frequency registers.  
Except now I split that relevant part into a function `PlayNoteCh` which applies to an existing channel number.
No support for RPN in this commit
=> implement MIDI features: pitch bend, (N)RPN tracking, bend sensitivity, hold pedal

src/opl/generator.cpp, src/opl/generator.h
Your velocity has broken my pitchbend.
The piano widget plays at full velocity, so no problem for it, but so doesn't my MIDI keyboard.
=> midi: make pitchbend velocity-aware

src/bank_editor.cpp, src/bank_editor.h, src/bank_editor.ui, src/opl/measurer.cpp, src/translations/opl3bankeditor_fr_FR.ts, src/translations/opl3bankeditor_ru_RU.ts
To make easier the measurer work with existing banks.
The completion of the progress dialog `doMeasurement` has been fixed. I have added a menu item, and at the same time I update my translation for this new text.
=> add menu action to measure a single instrument

src/opl/measurer.cpp
Add code which permits clean measurements of signal amplitudes.
I have not done any rigorous checks.
The code will take measures which same steps as before, with differences:
- it's going to accumulate up to N seconds of signal, as defined by the value `historyLength`.
- the signal will be windowed to ensure the side lobes will not add noise in the measurement.
- the window will be cached between successive measurements.
This measurement will have more overhead over than the previous one, but maybe not important compared to synthesizing OPL. The overhead can be limited by choosing a smaller `historyLength` (of which the default 1.0 value may be very excessive).
Below there are clean plots of the instrument "Sax" used for testing purposes.
=> clean amplitude measurements with window

CMakeLists.txt, src/resources/opl3_bank_editor.desktop
Installs the desktop file and the icons of all sizes in the `hicolor` theme.
(on the non-Windows non-Mac systems)
It needs an update of icon cache to recognize.
`sudo gtk-update-icon-cache -f /usr/share/icons/hicolor`
=> cmake: install desktop files and icons

CMakeLists.txt, FMBankEdit.pro, src/main.cpp, src/proxystyle.cpp, src/proxystyle.h
#88 
Proxy style from PGE editor.
May fix Windows combo box width problems. Not compatible with Qt4. To test.
=> add @Wohlstand's proxy style to fix QComboBox width

src/FileFormats/wopl/wopl_file.h
Fixes a recurrent typo in `wopl_file.h` comments
=> fix typo in WOPL file comments

src/audio.cpp, src/bank_editor.h
It's for the the piano tone problem found by papiezak.
Identical problem in OPL3BankEditor, identical patch
=> ignore unmatched key release events on keyboard

CMakeLists.txt, cmake/FindQwt.cmake
Proposing a safer way to find Qwt. (but not flawless)
When having Qwt for Qt4 installed, the system may pick up this version and create a OPL3-BE which links to both of Qt4 and Qt5 at the end of the cmake build.
As one can expect, the runtime segfaults sometime early in the startup process.
=> safer detection of libqwt

CMakeLists.txt, utils/measurer/measurer.cpp
Provide `measurer` as a very basic command line tool.
Usage is ```measurer input.wopl output.wopl```
=> provide the bank measurer as a CLI tool

src/bank_editor.cpp, src/bank_editor.h, src/controlls.cpp
#78 
Here's a change to implement blank entries as gray items.
Until `QListView` will be implemented, which is not an easy job.
Here are big changes made:
- initial instruments start as *blank*, not *empty*
- the name reloading update the "grayness" at the same time
- any change of *control* by widget is going to also turn the instrument non-blank if it was, and update the grayness (cf `afterChangeControlValue`)
- the functions `clear` (instrument, bank) are going to fill with blanks instead of empties
=> display blank entries in gray color

CMakeLists.txt
Fix the plots I noticed broken while testing many things.
`ENABLE_PLOTS` not enabled in libMeasurer.
=> fix the compile time definition of ENABLE_PLOTS

src/FileFormats/format_dro_importer.cpp
I think this fixes the importer problems.
On OPL2 hardware type: just ignore the upper register commands.
=> dro: don't pass high registers to chip in OPL2 case

src/bank_editor.cpp, src/bank_editor.h
The call `loadSettings()`→`initChip()` accesses `m_generator` before creation.
Initialize `m_generator` with null, and perform the `initChip()` a moment later.
=> fix a crash at startup with hardware OPL enabled

CMakeLists.txt, FMBankEdit.pro, src/FileFormats/ffmt_enums.h, src/FileFormats/ffmt_factory.cpp, src/FileFormats/format_misc_hsc.cpp, src/FileFormats/format_misc_hsc.h
#131
Support the 12 byte `ins` format HSC.
Samples are present in the `AdlibTracker2` folder as `ins` files. Not all these At2 samples are necessarily HSC.
It's because At2 will do special handling: it will load 3 kinds of `ins`, tried in succession.
(checking registers to be in their valid value domains)
- 12 byte, identical to SBI payload but header-less
- 12 byte, HSC payload
-  more than 12 bytes, "SAT" instrument
=> add the reader and writer of HSC instruments

CMakeLists.txt, FMBankEdit.pro, src/FileFormats/ffmt_enums.cpp, src/FileFormats/ffmt_enums.h, src/bank_editor.cpp, src/bank_editor.h, src/importer.cpp, src/importer.h, src/main.cpp, src/translations/opl3bankeditor_fr_FR.ts, src/translations/opl3bankeditor_ru_RU.ts
Adds a method to open (or import) any file kind: try as bank first, then imported bank, then instrument.
Having this, it can load all file kinds from command-line, and it will be possible to create the direct file association between OPL-BE and all the importables.
(also it makes repretitive test workflow for developing more pleasing)
=> Open or import

.travis.yml, CMakeLists.txt, FMBankEdit.pro, src/bank_editor.cpp, src/bank_editor.h, src/bank_editor.ui, src/hardware.cpp, src/hardware.h, src/hardware.ui, src/opl/chips/opl_serial_port.cpp, src/opl/chips/opl_serial_port.h, src/opl/chips/opl_serial_port.pri, src/opl/generator.cpp, src/opl/generator.h
#153
an attempt at OPL2 parallel port support.
I divided the hardware configuration dialog into 2 subgroups : for opl proxy, and serial port.
The groups which are not supported are hidden in runtime.
Since it's converted to a qt designer form, translations need an update of some existing strings + new ones.
note: QSerialPort is supported in Qt5 only.
It needs `ENABLE_HW_OPL_SERIAL_PORT` to enable it under the chips directory.
There is also a setting which stores the port name and the baud rate.
For testing. (cc @DhrBaksteen @Deftaudio)
=> Serial port

src/bank_editor.cpp, src/bank_editor.h, src/hardware.cpp, src/hardware.h, src/hardware.ui, src/opl/chips/opl_serial_port.cpp, src/opl/chips/opl_serial_port.h
#153
I add the drop-down menu which permits to choose "Arduino OPL2" as a selection of serial protocol.
Adding future protocols should take minimal effort from here.
=> hardware: add a setting to choose the serial protocol

.travis.yml
A static build script for macOS
result in `bin-release/opl3_bank_editor.app` (not deployed)
=> Automatic build for macOS

src/hardware.cpp, src/opl/chips/opl_serial_port.cpp, src/opl/chips/opl_serial_port.h
Add support of RetroWave OPL3 hardware protocol.
=> Add support of RetroWave OPL3 hardware protocol

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/reinstall-cmake.sh, .github/dependabot.yml
Adding this configuration file makes it easier to quickly setup an sandboxed build environment on any OS which already has devcontainer client support, for example with VSCode installed.
=> Add devcontainer config for easier builds on 
